language: java

jdk:
  - openjdk8

addons:
  ssh_known_hosts:
  - ftp.interlis.ch
  apt:
    packages:
    - python3
    - python3-pip

branches:
  only:
    - master
    - stable-core
    - stable

install: true

before_script:
    - python3 --version
    - virtualenv -p python3 my_py3
    - source my_py3/bin/activate # to activate the python3 environemt    
    - python -m pip --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org install docutils
    - python -m pip --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org install Pygments
    - python -m pip freeze

script: 
  - if [ $TRAVIS_BRANCH == "stable-core" ]; then ./gradlew :ili2c-core:jar :ili2c-core:test ; fi 
  - if [ $TRAVIS_BRANCH != "stable-core" ]; then ./gradlew -Drst2html=`which rst2html.py` jar test usrdoc ilidoc; fi
  
deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew --info -Drepos_dir=${repos_dir} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr}  bindist uploadArchives
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drst2html=`which rst2html.py` -Drepos_dir=${repos_dir} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr} '-Drelease=' bindist uploadArchives uploadBindist uploadDoc
    on:
      branch: stable
  - provider: script
    skip_cleanup: true
    script: ./gradlew -Drepos_dir=${repos_dir} -Drepos_pwd=${repos_pwd} -Drepos_usr=${repos_usr} '-Drelease=' :ili2c-core:uploadArchives
    on:
      branch: stable-core
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always